Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.provision :shell, path: "./scripts/bootstrap.sh"
  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.provider "virtualbox" do |v|
	v.memory = 4096
	v.cpus = 2
  end
end
